#!/bin/bash
#
# Phase 1.3: SSH Configuration Hardening
# Priority: CRITICAL
# Time: 30 minutes
#
# This script hardens SSH configuration with best practices
#

set -e  # Exit on error

echo "======================================"
echo "Phase 1.3: SSH Hardening"
echo "======================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check for SSH directory
if [ ! -d ~/.ssh ]; then
    echo "Creating ~/.ssh directory..."
    mkdir -p ~/.ssh
    chmod 700 ~/.ssh
fi

echo "Step 1: Setting proper permissions on SSH directory..."
chmod 700 ~/.ssh
echo -e "${GREEN}✓ SSH directory permissions set (700)${NC}"

echo ""
echo "Step 2: Checking for existing SSH keys..."
if [ -f ~/.ssh/id_ed25519 ]; then
    echo -e "${GREEN}✓ Ed25519 key found${NC}"
    chmod 600 ~/.ssh/id_ed25519
    chmod 644 ~/.ssh/id_ed25519.pub
    echo -e "${GREEN}✓ Key permissions set correctly${NC}"
else
    echo -e "${YELLOW}No Ed25519 key found.${NC}"
    echo "Would you like to create one? (y/n)"
    read -p "> " -n 1 -r
    echo

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Enter your email for the key comment:"
        read -p "> " SSH_EMAIL
        ssh-keygen -t ed25519 -C "$SSH_EMAIL" -f ~/.ssh/id_ed25519
        echo -e "${GREEN}✓ Ed25519 key created${NC}"
    fi
fi

echo ""
echo "Step 3: Checking if SSH key has a passphrase..."
if ssh-keygen -y -P "" -f ~/.ssh/id_ed25519 &>/dev/null; then
    echo -e "${YELLOW}⚠ WARNING: Your SSH key does not have a passphrase!${NC}"
    echo "A passphrase adds a second layer of security."
    echo "Would you like to add a passphrase now? (y/n)"
    read -p "> " -n 1 -r
    echo

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        ssh-keygen -p -f ~/.ssh/id_ed25519
        echo -e "${GREEN}✓ Passphrase added${NC}"
    else
        echo -e "${YELLOW}⚠ Continuing without passphrase (not recommended)${NC}"
    fi
else
    echo -e "${GREEN}✓ SSH key is protected with a passphrase${NC}"
fi

echo ""
echo "Step 4: Creating hardened SSH client configuration..."

# Backup existing config if it exists
if [ -f ~/.ssh/config ]; then
    echo "Backing up existing SSH config..."
    cp ~/.ssh/config ~/.ssh/config.backup.$(date +%Y%m%d_%H%M%S)
    echo -e "${GREEN}✓ Backup created${NC}"
fi

# Create new SSH config
cat > ~/.ssh/config << 'EOF'
# SSH Client Configuration - Hardened
# Generated by security-roadmap Phase 1.3

# Global defaults for all hosts
Host *
    # Use only Ed25519 keys
    IdentityFile ~/.ssh/id_ed25519

    # Security: Disable password authentication
    PasswordAuthentication no
    ChallengeResponseAuthentication no

    # Security: Disable less secure authentication methods
    PubkeyAuthentication yes

    # Connection keepalive
    ServerAliveInterval 60
    ServerAliveCountMax 3

    # Security: Use strongest ciphers (in order of preference)
    Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com

    # Security: Use strongest MACs
    MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

    # Security: Use strongest key exchange algorithms
    KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512

    # Security: Use only Ed25519 host keys
    HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256

    # Performance: Enable compression
    Compression yes

    # Security: Hash known hosts
    HashKnownHosts yes

    # Use SSH protocol 2 only
    Protocol 2

# GitHub configuration
Host github.com
    User git
    IdentityFile ~/.ssh/id_ed25519
    IdentitiesOnly yes

# GitLab configuration (if needed)
Host gitlab.com
    User git
    IdentityFile ~/.ssh/id_ed25519
    IdentitiesOnly yes

# Add your own host configurations below
# Example:
# Host myserver
#     HostName 192.168.1.100
#     User myusername
#     Port 22
#     IdentityFile ~/.ssh/id_ed25519
EOF

chmod 600 ~/.ssh/config
echo -e "${GREEN}✓ SSH config created and secured${NC}"

echo ""
echo "Step 5: Setting up SSH agent..."
if [ -z "$SSH_AUTH_SOCK" ]; then
    echo "SSH agent not running. Starting..."
    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_ed25519
    echo -e "${GREEN}✓ SSH agent started and key added${NC}"

    echo ""
    echo "Note: Add the following to your ~/.bashrc or ~/.zshrc to auto-start ssh-agent:"
    echo ""
    echo "# Start SSH agent"
    echo "if [ -z \"\$SSH_AUTH_SOCK\" ]; then"
    echo "    eval \"\$(ssh-agent -s)\" > /dev/null"
    echo "    ssh-add ~/.ssh/id_ed25519 2>/dev/null"
    echo "fi"
else
    echo -e "${GREEN}✓ SSH agent is already running${NC}"
    ssh-add ~/.ssh/id_ed25519 2>/dev/null || echo "Key already added to agent"
fi

echo ""
echo "Step 6: Testing SSH configuration..."
if ssh -T git@github.com 2>&1 | grep -q "successfully authenticated"; then
    echo -e "${GREEN}✓ GitHub SSH connection successful${NC}"
else
    echo -e "${YELLOW}⚠ Could not verify GitHub connection (this is normal if not set up yet)${NC}"
fi

echo ""
echo "Step 7: Setting up SSH known_hosts..."
if [ ! -f ~/.ssh/known_hosts ]; then
    touch ~/.ssh/known_hosts
    chmod 644 ~/.ssh/known_hosts
fi

# Add GitHub's host keys
ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts 2>/dev/null
echo -e "${GREEN}✓ GitHub host key added${NC}"

echo ""
echo -e "${GREEN}======================================"
echo "SSH Hardening Complete!"
echo "======================================${NC}"
echo ""
echo "Configuration summary:"
echo "  ✓ SSH directory permissions: 700"
echo "  ✓ Private key permissions: 600"
echo "  ✓ Public key permissions: 644"
echo "  ✓ Config file permissions: 600"
echo "  ✓ Strong ciphers configured"
echo "  ✓ Strong key exchange algorithms"
echo "  ✓ Password authentication disabled"
echo ""
echo "Your SSH public key (add to GitHub/servers):"
echo "========================================="
cat ~/.ssh/id_ed25519.pub
echo "========================================="
echo ""
echo "Useful commands:"
echo "  - Test connection: ssh -T git@github.com"
echo "  - List loaded keys: ssh-add -l"
echo "  - Add key to agent: ssh-add ~/.ssh/id_ed25519"
echo "  - View SSH config: cat ~/.ssh/config"
echo ""
echo "✓ Phase 1.3 Complete"
