#!/bin/bash
#
# Phase 1.4: Automated Backup Setup
# Priority: CRITICAL for dev work
# Time: 1 hour
#
# This script sets up automated encrypted backups using restic
#

set -e  # Exit on error

echo "======================================"
echo "Phase 1.4: Backup Setup"
echo "======================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "Step 1: Installing restic..."
if ! command -v restic &> /dev/null; then
    sudo apt update
    sudo apt install -y restic
    echo -e "${GREEN}✓ Restic installed${NC}"
else
    echo -e "${GREEN}✓ Restic is already installed${NC}"
    restic version
fi

echo ""
echo "Step 2: Configuring backup location..."
echo ""
echo "Where would you like to store backups?"
echo "Options:"
echo "  1. External drive (e.g., /media/username/backup-drive)"
echo "  2. Network location (e.g., /mnt/nas/backups)"
echo "  3. Cloud storage (requires additional setup - S3, B2, etc.)"
echo "  4. Custom path"
echo ""
read -p "Choose option (1-4): " -n 1 -r BACKUP_OPTION
echo ""

case $BACKUP_OPTION in
    1)
        echo "Enter the path to your external drive:"
        echo "(Example: /media/$USER/MyDrive)"
        read -p "> " BACKUP_BASE
        ;;
    2)
        echo "Enter the network path:"
        echo "(Example: /mnt/nas/backups)"
        read -p "> " BACKUP_BASE
        ;;
    3)
        echo "Cloud storage setup requires additional configuration."
        echo "For now, enter a local path and you can reconfigure later."
        read -p "> " BACKUP_BASE
        ;;
    4)
        echo "Enter custom backup path:"
        read -p "> " BACKUP_BASE
        ;;
    *)
        echo "Invalid option. Using default: ~/backups"
        BACKUP_BASE="$HOME/backups"
        ;;
esac

# Create backup repo path
BACKUP_REPO="$BACKUP_BASE/restic-repo"
echo "Backup repository will be: $BACKUP_REPO"

# Check if path exists
if [ ! -d "$BACKUP_BASE" ]; then
    echo "Creating backup directory..."
    mkdir -p "$BACKUP_BASE"
fi

echo ""
echo "Step 3: Generating secure backup password..."
BACKUP_PASSWORD_FILE="$HOME/.backup-password"

if [ -f "$BACKUP_PASSWORD_FILE" ]; then
    echo -e "${YELLOW}⚠ Backup password file already exists${NC}"
    read -p "Overwrite? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Using existing password file"
    else
        openssl rand -base64 32 > "$BACKUP_PASSWORD_FILE"
        chmod 600 "$BACKUP_PASSWORD_FILE"
        echo -e "${GREEN}✓ New backup password generated${NC}"
    fi
else
    openssl rand -base64 32 > "$BACKUP_PASSWORD_FILE"
    chmod 600 "$BACKUP_PASSWORD_FILE"
    echo -e "${GREEN}✓ Backup password generated${NC}"
fi

echo ""
echo -e "${YELLOW}IMPORTANT: Save this password in your password manager!${NC}"
echo "Backup password:"
echo "========================================="
cat "$BACKUP_PASSWORD_FILE"
echo "========================================="
echo ""
read -p "Press Enter after you've saved the password..."

echo ""
echo "Step 4: Initializing restic repository..."
if [ -d "$BACKUP_REPO" ]; then
    echo -e "${YELLOW}⚠ Repository already exists at $BACKUP_REPO${NC}"
else
    restic init --repo "$BACKUP_REPO" --password-file "$BACKUP_PASSWORD_FILE"
    echo -e "${GREEN}✓ Repository initialized${NC}"
fi

echo ""
echo "Step 5: Creating backup script..."
mkdir -p ~/.local/bin

cat > ~/.local/bin/backup-home.sh << EOF
#!/bin/bash
#
# Automated backup script using restic
# Generated by security-roadmap Phase 1.4
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
BACKUP_REPO="$BACKUP_REPO"
BACKUP_PASSWORD_FILE="$HOME/.backup-password"
LOG_FILE="$HOME/.backup.log"

# Timestamp
echo "=========================================" | tee -a "\$LOG_FILE"
echo "Backup started: \$(date)" | tee -a "\$LOG_FILE"
echo "=========================================" | tee -a "\$LOG_FILE"

# Check if password file exists
if [ ! -f "\$BACKUP_PASSWORD_FILE" ]; then
    echo -e "\${RED}Error: Backup password file not found at \$BACKUP_PASSWORD_FILE\${NC}" | tee -a "\$LOG_FILE"
    exit 1
fi

# Check if repo exists
if [ ! -d "\$BACKUP_REPO" ]; then
    echo -e "\${RED}Error: Backup repository not found at \$BACKUP_REPO\${NC}" | tee -a "\$LOG_FILE"
    exit 1
fi

# What to backup
BACKUP_PATHS=(
    "$HOME/dev-ops"
    "$HOME/.ssh"
    "$HOME/.gnupg"
)

# Add optional paths if they exist
[ -d "$HOME/projects" ] && BACKUP_PATHS+=("$HOME/projects")
[ -d "$HOME/Documents" ] && BACKUP_PATHS+=("$HOME/Documents")
[ -d "$HOME/.password-store" ] && BACKUP_PATHS+=("$HOME/.password-store")
[ -d "$HOME/.config" ] && BACKUP_PATHS+=("$HOME/.config")

# What to exclude
EXCLUDE_PATTERNS=(
    "*.log"
    "*.tmp"
    "node_modules"
    "__pycache__"
    ".cache"
    ".npm"
    ".cargo"
    ".rustup"
    "target"
    "build"
    "dist"
    ".git/objects"
    ".venv"
    "venv"
)

# Build exclude arguments
EXCLUDE_ARGS=""
for pattern in "\${EXCLUDE_PATTERNS[@]}"; do
    EXCLUDE_ARGS="\$EXCLUDE_ARGS --exclude=\$pattern"
done

echo "Backing up paths:" | tee -a "\$LOG_FILE"
for path in "\${BACKUP_PATHS[@]}"; do
    echo "  - \$path" | tee -a "\$LOG_FILE"
done
echo ""

# Perform backup
echo "Starting backup..." | tee -a "\$LOG_FILE"
if restic backup "\${BACKUP_PATHS[@]}" \\
    --repo "\$BACKUP_REPO" \\
    --password-file "\$BACKUP_PASSWORD_FILE" \\
    \$EXCLUDE_ARGS \\
    --verbose 2>&1 | tee -a "\$LOG_FILE"; then

    echo -e "\${GREEN}✓ Backup completed successfully\${NC}" | tee -a "\$LOG_FILE"

    # Cleanup old backups (keep last 7 daily, 4 weekly, 12 monthly)
    echo ""
    echo "Cleaning up old backups..." | tee -a "\$LOG_FILE"
    restic forget --repo "\$BACKUP_REPO" \\
        --password-file "\$BACKUP_PASSWORD_FILE" \\
        --keep-daily 7 \\
        --keep-weekly 4 \\
        --keep-monthly 12 \\
        --prune 2>&1 | tee -a "\$LOG_FILE"

    echo -e "\${GREEN}✓ Cleanup completed\${NC}" | tee -a "\$LOG_FILE"

    # Show backup stats
    echo ""
    echo "Backup statistics:" | tee -a "\$LOG_FILE"
    restic stats --repo "\$BACKUP_REPO" --password-file "\$BACKUP_PASSWORD_FILE" 2>&1 | tee -a "\$LOG_FILE"

else
    echo -e "\${RED}✗ Backup failed!\${NC}" | tee -a "\$LOG_FILE"
    exit 1
fi

echo ""
echo "Backup finished: \$(date)" | tee -a "\$LOG_FILE"
EOF

chmod +x ~/.local/bin/backup-home.sh
echo -e "${GREEN}✓ Backup script created${NC}"

echo ""
echo "Step 6: Creating restore script..."
cat > ~/.local/bin/restore-backup.sh << EOF
#!/bin/bash
#
# Restore from backup
# Generated by security-roadmap Phase 1.4
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
BACKUP_REPO="$BACKUP_REPO"
BACKUP_PASSWORD_FILE="$HOME/.backup-password"

echo "======================================"
echo "Restore from Backup"
echo "======================================"
echo ""

# List available snapshots
echo "Available snapshots:"
restic snapshots --repo "\$BACKUP_REPO" --password-file "\$BACKUP_PASSWORD_FILE"

echo ""
echo "Enter snapshot ID to restore (or 'latest'):"
read -p "> " SNAPSHOT_ID

echo ""
echo "Enter restore destination (e.g., /tmp/restore):"
read -p "> " RESTORE_PATH

mkdir -p "\$RESTORE_PATH"

echo ""
echo "Restoring snapshot \$SNAPSHOT_ID to \$RESTORE_PATH..."
restic restore "\$SNAPSHOT_ID" \\
    --repo "\$BACKUP_REPO" \\
    --password-file "\$BACKUP_PASSWORD_FILE" \\
    --target "\$RESTORE_PATH" \\
    --verbose

echo ""
echo -e "\${GREEN}✓ Restore completed\${NC}"
echo "Files restored to: \$RESTORE_PATH"
EOF

chmod +x ~/.local/bin/restore-backup.sh
echo -e "${GREEN}✓ Restore script created${NC}"

echo ""
echo "Step 7: Running initial backup..."
read -p "Run initial backup now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    ~/.local/bin/backup-home.sh
else
    echo "Skipping initial backup. Run manually: ~/.local/bin/backup-home.sh"
fi

echo ""
echo "Step 8: Setting up automated backups with cron..."
read -p "Schedule daily backups at 2 AM? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Remove existing backup cron jobs
    (crontab -l 2>/dev/null | grep -v "backup-home.sh" || true) | crontab -

    # Add new cron job
    (crontab -l 2>/dev/null; echo "0 2 * * * $HOME/.local/bin/backup-home.sh") | crontab -

    echo -e "${GREEN}✓ Daily backups scheduled${NC}"
    echo "Current crontab:"
    crontab -l
else
    echo "Skipping cron setup. You can run backups manually."
fi

echo ""
echo -e "${GREEN}======================================"
echo "Backup Setup Complete!"
echo "======================================${NC}"
echo ""
echo "Configuration:"
echo "  Repository: $BACKUP_REPO"
echo "  Password file: $BACKUP_PASSWORD_FILE"
echo "  Backup script: ~/.local/bin/backup-home.sh"
echo "  Restore script: ~/.local/bin/restore-backup.sh"
echo "  Log file: ~/.backup.log"
echo ""
echo "Useful commands:"
echo "  - Run backup: ~/.local/bin/backup-home.sh"
echo "  - List backups: restic snapshots --repo $BACKUP_REPO --password-file $BACKUP_PASSWORD_FILE"
echo "  - Restore: ~/.local/bin/restore-backup.sh"
echo "  - Check integrity: restic check --repo $BACKUP_REPO --password-file $BACKUP_PASSWORD_FILE"
echo "  - View log: tail -f ~/.backup.log"
echo ""
echo -e "${YELLOW}IMPORTANT:${NC}"
echo "  1. Save your backup password in a password manager"
echo "  2. Test restore process monthly"
echo "  3. Store password file securely"
echo "  4. Consider off-site backup copy"
echo ""
echo "✓ Phase 1.4 Complete"
