#!/bin/bash
#
# Phase 1.5: System Updates Configuration
# Priority: HIGH
# Time: 15 minutes
#
# This script configures automatic security updates
#

set -e  # Exit on error

echo "======================================"
echo "Phase 1.5: System Updates"
echo "======================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: This script must be run with sudo${NC}"
    exit 1
fi

echo "Step 1: Installing unattended-upgrades..."
if ! command -v unattended-upgrades &> /dev/null; then
    apt update
    apt install -y unattended-upgrades apt-listchanges
    echo -e "${GREEN}✓ unattended-upgrades installed${NC}"
else
    echo -e "${GREEN}✓ unattended-upgrades is already installed${NC}"
fi

echo ""
echo "Step 2: Configuring automatic security updates..."
dpkg-reconfigure -plow unattended-upgrades
echo -e "${GREEN}✓ Automatic updates configured${NC}"

echo ""
echo "Step 3: Configuring update behavior..."

# Backup original config
if [ -f /etc/apt/apt.conf.d/50unattended-upgrades ]; then
    cp /etc/apt/apt.conf.d/50unattended-upgrades /etc/apt/apt.conf.d/50unattended-upgrades.backup.$(date +%Y%m%d)
fi

# Configure unattended-upgrades
cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
// Automatically upgrade packages from these origins
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};

// List of packages to not update
Unattended-Upgrade::Package-Blacklist {
    // Add packages you don't want auto-updated here
    // "vim";
    // "nginx";
};

// Split the upgrade into smallest possible chunks so interruptions don't cause issues
Unattended-Upgrade::MinimalSteps "true";

// Email alerts (requires mail setup)
// Unattended-Upgrade::Mail "your-email@example.com";
Unattended-Upgrade::MailReport "on-change";

// Remove unused automatically installed kernel-related packages
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";

// Remove unused dependencies
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Auto-reboot if required (careful with this!)
Unattended-Upgrade::Automatic-Reboot "false";

// Auto-reboot time (if enabled)
Unattended-Upgrade::Automatic-Reboot-Time "02:00";

// Logging
Unattended-Upgrade::SyslogEnable "true";
Unattended-Upgrade::SyslogFacility "daemon";
EOF

echo -e "${GREEN}✓ Update configuration applied${NC}"

echo ""
echo "Step 4: Updating package lists..."
apt update
echo -e "${GREEN}✓ Package lists updated${NC}"

echo ""
echo "Step 5: Checking for available updates..."
apt list --upgradable 2>/dev/null | grep -v "Listing..." || echo "No updates available"

echo ""
read -p "Apply all available updates now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Upgrading system..."
    apt upgrade -y
    echo -e "${GREEN}✓ System upgraded${NC}"
else
    echo "Skipping system upgrade. Run 'sudo apt upgrade' when ready."
fi

echo ""
echo "Step 6: Checking for firmware updates..."
if command -v fwupdmgr &> /dev/null; then
    echo "Refreshing firmware database..."
    fwupdmgr refresh --force || true
    echo ""
    echo "Checking for firmware updates..."
    if fwupdmgr get-updates 2>&1 | grep -q "Devices with no available firmware updates"; then
        echo -e "${GREEN}✓ All firmware is up to date${NC}"
    else
        echo -e "${YELLOW}Firmware updates available:${NC}"
        fwupdmgr get-updates
        echo ""
        read -p "Install firmware updates? (y/n) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            fwupdmgr update
            echo -e "${GREEN}✓ Firmware updated${NC}"
        fi
    fi
else
    echo -e "${YELLOW}fwupdmgr not installed. Installing...${NC}"
    apt install -y fwupd
    echo -e "${GREEN}✓ fwupd installed${NC}"
fi

echo ""
echo "Step 7: Enabling automatic update timer..."
systemctl enable --now apt-daily.timer
systemctl enable --now apt-daily-upgrade.timer
echo -e "${GREEN}✓ Update timers enabled${NC}"

echo ""
echo "Step 8: Creating update check script..."
cat > /usr/local/bin/check-updates.sh << 'EOF'
#!/bin/bash
#
# Check for system updates
# Generated by security-roadmap Phase 1.5
#

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "======================================"
echo "System Update Check"
echo "Date: $(date)"
echo "======================================"
echo ""

# Update package lists
echo "Updating package lists..."
apt update -qq

# Check for upgradable packages
UPDATES=$(apt list --upgradable 2>/dev/null | grep -c "upgradable")

if [ "$UPDATES" -gt 0 ]; then
    echo -e "${YELLOW}$UPDATES updates available:${NC}"
    apt list --upgradable 2>/dev/null | grep -v "Listing..."
    echo ""
    echo "Run 'sudo apt upgrade' to install updates"
else
    echo -e "${GREEN}✓ System is up to date${NC}"
fi

echo ""
echo "Security updates:"
apt list --upgradable 2>/dev/null | grep -i security || echo "No security updates"

echo ""
echo "Last update check: $(stat -c %y /var/lib/apt/periodic/update-success-stamp 2>/dev/null || echo 'Never')"
echo "Last upgrade: $(stat -c %y /var/log/apt/history.log 2>/dev/null || echo 'Unknown')"
EOF

chmod +x /usr/local/bin/check-updates.sh
echo -e "${GREEN}✓ Update check script created${NC}"

echo ""
echo "Step 9: Verifying configuration..."
echo "Automatic update status:"
systemctl status unattended-upgrades --no-pager | head -10

echo ""
echo -e "${GREEN}======================================"
echo "System Updates Complete!"
echo "======================================${NC}"
echo ""
echo "Configuration:"
echo "  ✓ Automatic security updates: ENABLED"
echo "  ✓ Update timers: ACTIVE"
echo "  ✓ Firmware updates: CONFIGURED"
echo "  ✓ Auto-reboot: DISABLED (safe default)"
echo ""
echo "Update schedule:"
echo "  - Security updates: Automatic daily"
echo "  - Package list refresh: Daily"
echo "  - Regular updates: Manual (sudo apt upgrade)"
echo ""
echo "Useful commands:"
echo "  - Check for updates: sudo /usr/local/bin/check-updates.sh"
echo "  - Apply updates: sudo apt update && sudo apt upgrade"
echo "  - View update history: cat /var/log/apt/history.log"
echo "  - View unattended-upgrades log: cat /var/log/unattended-upgrades/unattended-upgrades.log"
echo "  - Firmware updates: sudo fwupdmgr get-updates"
echo ""
echo "✓ Phase 1.5 Complete"
